### ISSUE TITLE
Link to paper please?

### ISSUE THREAD

**Issue by JacobFV** [zhudotexe/fastlmi#1]
Hi @zhudotexe,

Thanks for making this repo. We're making a repo [LMI](https://github.com/ComputaCo/lmi.git) and we are considering using fastlmi in it. Could you help us find the paper referenced in the citation?

```
@software{Zhu_FastLMI_2023,
    author = {Zhu, Andrew},
    doi = {10.5281/zenodo.7916737},
    month = may,
    title = {{FastLMI}},
    url = {https://github.com/zhudotexe/fastlmi},
    version = {0.1.0},
    year = {2023}
}
```

I couldn't find the paper. Your help would be appreciated. Thanks!

**Comment by zhudotexe** [comment]
Hi Jacob, thanks for your interest! We actually don't have an associated paper for this repo - this GitHub repository is the primary artifact and you can cite it with that bibtex.

**Comment by JacobFV** [comment]
Okay. Thanks!

On Dec 13, 2023, at 20:58, Andrew Zhu ***@***.***> wrote:

﻿

Hi Jacob, thanks for your interest! We actually don't have an associated paper for this repo - this GitHub repository is the primary artifact and you can cite it with that bibtex.
